### ISSUE TITLE
Please provide a tutorial

### ISSUE THREAD

**Issue by Chris2011** [Mario-S/netbeans-electron-support#1]
I'm new in this, I only wanted to see whether I can create an electron app with netbeans or not. So I thought that there is a new project type or project template for this but no there isn't. There is only an option to add the executable.

I installed electron via "npm install -g electron-prebuilt" on a Windows 7. So the executable is here exactly what? I have a folder inside my username folder called .electron, there is a zip archive in it. But I think this is not the right one, or? It would be the electron.cmd (For windows) correct?

So for me it would be nice if you can update your readme with a bit more description. For what does the plugin stand for. Only to execute electron apps or to build it and execute it? Are there any project templates etc. pp.

Regards

Chris

**Comment by Mario-S** [comment]
Hi Chris,

thanks a lot for your feedback! 

I created this plugin, because I was not satisfied with the existing node.js-plugin. Maybe a future version of the node.js-plugin will make this one obsolete.

I added a very simple template for an electron app. However this is not the final projet layout and configuration. I think it should be like a typical HTML5 project. But it is work in progress.

The GUI for the executable was my first attempt, and it can still be used if you haven't installed the electron in your node.js with the global option (-g). But in your case it is not really necessary, because the main javascript (main.js) of an electron app can also be launched with the command line. This is what the plugin is using, when the path to the executable does not exists. 

To launch you app, either right click on a javascript file in the project browser or in the editor and you will see 'Run with Electron' or 'Debug with Electron'. The default Run action for a electron project should also work.

I hope this helps a bit.

Regards,
Mario

**Comment by Chris2011** [comment]
Which version of netbeans do you use? Node.js is not a plugin anymore, it is now a build it since NB v8.1, which is in RC2 status atm. So give it a try, it is very very cool, if you didn't try it yet.

Where can I find the project template or is this the part, which is not implemented yet? My interests are in your code too, did you extend the projectCustomizer to add things to the property section of a specific project type?

I thought with your plugin, because of the resources like the icons, it is possible to have a new project type and so on.


Cheers

Chris

**Comment by Mario-S** [comment]
I'm using the version 8.0.2 of NetBeans currently. I haven't checked out the Node.js support in 8.1 yet. Yeah, it might be a option, or even the foundation for this plugin.

Damn, the zip file with the template was not pushed. I might fix it this evening;-)

As I said before, it is still work in progress, and one of my next task is to extends the property section, which you mentioned.

Anyway, you are very welcome to contribute.

Regards,
Mario

**Comment by Chris2011** [comment]
Thx. Is it possible to provide a nbm file as a release file too? At my working place, I can't build it, because of the maven repositories, everything is fine at home. Would be nice. Thx.

**Comment by Mario-S** [comment]
sure, will add it later under a folder 'bin'.

Cheers
