### ISSUE TITLE
Can't install nbm file, External Browser is requested in impl. version

### ISSUE THREAD

**Issue by Chris2011** [Mario-S/netbeans-electron-support#2]
When I try to install your nbm file, which you've uploaded into your github repo, I got this error: 
![electronnb](https://cloud.githubusercontent.com/assets/795658/11143064/9af2ccb0-89f2-11e5-8d12-207dbbef872d.PNG)

I use Netbeans 8.1 on Windows 10.

Regards

Chris

**Comment by mario-s** [comment]
The reason behind this issue is that Electron requires Chrome for debugging: http://electron.atom.io/docs/v0.34.0/tutorial/debugging-main-process/

However to use the chrome browser in NetBeans my module had to be either a friend of the browser module or use the implementation. I decided to use the implementation for the beginning.

You get this message because the module requires an old implementation from version 8.0.2. You can fix it by yourself by replacing the implementation version in the module.xml and rebuild the plugin. However I don't think it makes sense to update this plugin. As you already mentioned, the Node.js support in NetBeans 8.1 is much better than it used to be.

So to run an Electron app from NetBeans 8.1 you don't need this plugin at all. Instead extend the package.json for a HTML5 client application like this:

{
    "name": "foo-bar",
    "version": "1.0.0",
    "main"    : "public_html/main.js",
    "scripts": {
        "electron run": "electron ."
     }
}
